# [toolchain]
# profile = "minimal"
# # use the nightly version of the last stable toolchain, see <https://forge.rust-lang.org/>
# channel = "nightly-2024-02-25"
# components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]

[toolchain]
profile = "minimal"
# use the nightly version of the last stable toolchain, see <https://forge.rust-lang.org/>
# channel = "nightly-2023-07-14" nightly-2024-07-13
channel = "nightly-2024-07-13"
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
