# [toolchain]
# profile = "minimal"
# # use the nightly version of the last stable toolchain, see <https://forge.rust-lang.org/>
# channel = "nightly-2024-02-25"
# channel = "nightly-2024-07-13"
# 1.73.0-nightly
# components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]

[toolchain]
profile = "minimal"
# use the nightly version of the last stable toolchain, see <https://forge.rust-lang.org/>
channel = "1.79.0-nightly"
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
